---
blueprint:
  name: Brilliant Heating
  author: Chris Wood
  description: >
    # Brilliant Heating
  domain: automation
  input:
    input_sensors:
      name: Input Entities (Required)
      description: >
        The following entities are the primary input triggers for your
        automation.<br>
      icon: mdi:home-import-outline
      collapsed: true
      input:
        occupancy_sensor_entity:
          name: Room Occupancy Sensor (Required)
          description: >
            The binary sensor detecting occupancy or motion in the room.<br>
            _Best practice: If you have more than one occupancy sensor, create
            a Binary Sensor Group Helper which contains all of your occupancy
            sensors_
          selector:
            entity:
              domain:
                - binary_sensor
              device_class:
                - occupancy
                - motion
              multiple: false
              reorder: false
        climate_entity:
          name: Room Climate Sensor (Required)
          description: >
            The `climate` sensor entity which controls the heating in the
            room.<br>
            This would typically be the climate sensor for your TRV or
            per-room thermostat
          selector:
            entity:
              domain:
                - climate
              multiple: false
              reorder: false
    eco_mode_settings:
      name: Eco Mode Settings (Required)
      description: >
        How does the room heating work when there is no-one in the room?<br>
        These are your base settings for the room, and you can provide them in
        a number of different ways.
      icon: mdi:leaf-circle-outline
      input:
        eco_mode_type:
          name: Eco Mode Type (Required)
          description: >
            Some climate entities have modes which allow you to turn off the
            device or set it to an Auto mode. Auto mode typically utilises a
            schedule which you'll have defined somewhere - perhaps in the app
            which you got with your heating system components
            If these modes exist for your climate entity, then the automation
            can use one of them as your Eco mode for the room.<br>
            If your entity doesn't support these modes, then you must provide
            a `schedule` entity to use instead.
          default: 'climate_off_mode'
          selector:
            select:
              options:
                - label: >
                    Climate Entity Off Mode
                  value: climate_off_mode
                - label: >
                    Climate Entity Auto Mode
                  value: climate_auto_mode
                - label: >
                    Eco Schedule Entity
                  value: schedule_entity
        eco_schedule_entity:
          name: Eco Schedule Entity (Required if using Eco Schedule Entity mode)
          description: >
            The `schedule` entity defining times and temperatures to use when
            the room is in Eco Mode
          selector:
            entity:
              domain:
                - schedule
              multiple: false
              reorder: false
        default_eco_temperature:
          name: Default Eco Schedule Temperature (Required)
          description: >
            The temperature to use by default with the Eco Schedule.
            You can override this using e.g. `temperature: 20.5` in the `data`
            section of each schedule slot
          default: 16
          selector:
            number:
              min: 5
              max: 30
              unit_of_measurement: C
              step: 0.5
              mode: slider
    occupied_mode_settings:
      name: Occupied Mode Settings (Required)
      description: >
        How does the room heating work when the room is occupied?<br>
        These are your _comfort_ settings for the room.<br>
        The delay settings may improve the efficiency of your heating system
        by ensuring that someone passing through the room doesn't trigger
        Occupied Mode. In the same way, delaying Occupied mode from turning
        off helps cope with people leaving the room for short periods.
      icon: mdi:account-circle-outline
      input:
        occupied_schedule_entity:
          name: Occupied Schedule Entity (Required)
          description: >
            The `schedule` entity defining times and temperatures to use when
            the room is occupied
          selector:
            entity:
              domain:
                - schedule
              multiple: false
              reorder: false
        default_occupied_temperature:
          name: Default Occupied Schedule Temperature (Required)
          description: >
            The temperature to use by default with the Occupied Schedule.
            You can override this using e.g. `temperature: 20.5` in the `data`
            section of each schedule slot
          default: 19
          selector:
            number:
              min: 5
              max: 30
              unit_of_measurement: C
              step: 0.5
              mode: slider
        occupied_schedule_start_delay_duration:
          name: Occupied Schedule Start Delay (Required)
          description: >
            The length of time occupancy is required for before the Occupied
            Schedule is used
          default: '00:04:00'
          selector:
            duration:
              enable_day: false
        occupied_schedule_end_delay_duration:
          name: Occupied Schedule End Delay (Required)
          description: >
            The length of time following occupancy clearing before heating
            reverts to the eco schedule
          default: '00:15:00'
          selector:
            duration:
              enable_day: false
    off_mode_settings:
      name: Off Mode Settings (Required)
      description: >
        How do we turn off your climate entity?<br>
        If your climate entity has an `Off` Mode, then you should choose
        this.<br>
        If this doesn't exist, we'll use a temperature of your choosing.
      icon: mdi:stop-circle-outline
      input:
        off_mode_type:
          name: Off Mode Type (Required)
          description: >
            Select `Off` Mode, if your climate entity supports it
          default: off_mode
          selector:
            select:
              options:
                - label: Climate Entity Off Mode
                  value: off_mode
                - label: Set Climate Entity Temperature
                  value: temperature
        off_mode_temperature:
          name: Off Mode Temperature
          description: >
            Off temp
          selector:
            choose:
              choices:
                Celcius:
                  selector:
                    number:
                      min: 5
                      max: 30
                      unit_of_measurement: °C
                      step: 0.5
                      mode: slider
                Fahrenheit:
                  selector:
                    number:
                      min: 40
                      max: 85
                      unit_of_measurement: °F
                      step: 1
                      mode: slider
    state_helpers:
      name: State Helpers (Required)
      description: >
        The following entities are used by the automation to hold state.<br>
      icon: mdi:state-machine
      collapsed: true
      input:
        heating_mode_status_entity:
          name: Heating Mode Status Helper (Required)
          description: >
            Requires an `input_text` helper
          selector:
            entity:
              domain:
                - input_text
              multiple: false
              reorder: false
    optional_scenes:
      name: Trigger Scenes (Optional)
      description: >
        The automation has a number of trigger points where you might want
        to take actions. We allow this through the use of scenes.<br>
        For instance, imagine your occupancy sensor has a controllable LED.
        When the automation actives, you could turn on the LED, and when it
        becomes inactive, you could turn it off.<br>
        This optional section provides you the ability to run scenes at each
        of the useful state changes in the automation.<br>
        Provide a scene for each of the trigger points you want to control,
        and just leave the others blank.
      icon: mdi:palette
      collapsed: true
      input:
        occupied_schedule_applied_scene:
          name: Occupied Schedule Applied (optional)
          description: >
            Triggers when Occupied Schedule is applied, following the
            start delay
          default:
          selector:
            entity:
              domain: scene
              multiple: false
              reorder: false
        eco_schedule_applied_scene:
          name: Eco Schedule Applied (optional)
          description: >
            Triggers when Eco Schedule is applied, following the
            end delay
          default:
          selector:
            entity:
              domain: scene
              multiple: false
              reorder: false

  source_url: >
    https://raw.githubusercontent.com/sprockers/homeassistant-blueprints/refs/heads/main/brilliant-heating.yaml
mode: single

variables:
  occupied_schedule_entity: !input occupied_schedule_entity
  default_occupied_temperature: !input default_occupied_temperature
  occupied_schedule_applied_scene: !input occupied_schedule_applied_scene
  eco_mode_type: !input eco_mode_type
  default_eco_temperature: !input default_eco_temperature

trigger_variables:
  occupancy_sensor_entity: !input occupancy_sensor_entity

triggers:

  - trigger: state
    entity_id: !input occupancy_sensor_entity
    to: 'on'
    for: !input occupied_schedule_start_delay_duration
    id: TurnOccupiedScheduleOn
  - trigger: state
    entity_id: !input occupied_schedule_entity
    attribute: temperature
    id: TurnOccupiedScheduleOn
  - trigger: state
    entity_id: !input occupancy_sensor_entity
    to: 'off'
    for: !input occupied_schedule_end_delay_duration
    id: TurnOccupiedScheduleOff
  - trigger: state
    entity_id: !input occupied_schedule_entity
    to: 'off'
    id: TurnOccupiedScheduleOff


action:
  - choose:

      - conditions:
          - condition: trigger
            id: TurnOccupiedScheduleOn
          - condition: state
            entity_id: !input occupancy_sensor_entity
            state: 'on'
          - condition: state
            entity_id: !input occupied_schedule_entity
            state: 'on'
        sequence:
          - action: climate.set_temperature
            entity_id: !input climate_entity
            hvac_mode: "heat"
            temperature: >
              {{ state_attr(occupied_schedule_entity, 'temperature')
              if state_attr(occupied_schedule_entity, 'temperature')
              is not none else default_occupied_temperature }}
          - action: input_text.set_value
            target:
              entity_id: !input heating_mode_status_entity
            data:
              value: 'Occupied'
          - if:
              - condition: template
                value_template: >
                  {{ occupied_schedule_applied_scene is not none }}
            then:
              - action: scene.turn_on
                target:
                  entity_id: !input occupied_schedule_applied_scene

      - conditions:
          - condition: trigger
            id: TurnOccupiedScheduleOff
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: >
                      {{ eco_mode_type == 'climate_off_mode' }}
                sequence:
                  - action: climate.set_hvac_mode
                    entity_id: !input climate_entity
                    hvac_mode: 'off'
              - conditions:
                  - condition: template
                    value_template: >
                      {{ eco_mode_type == 'climate_auto_mode' }}
                sequence:
                  - action: climate.set_hvac_mode
                    entity_id: !input climate_entity
                    hvac_mode: 'auto'
              - conditions:
                  - condition: template
                    value_template: >
                      {{ eco_mode_type == 'schedule_entity' }}
                sequence:
                  - action: climate.set_temperature
                    entity_id: !input climate_entity
                    hvac_mode: "heat"
                    temperature: >
                      {{ state_attr(eco_schedule_entity, 'temperature')
                      if state_attr(eco_schedule_entity, 'temperature')
                      is not none else default_eco_temperature }}
          - action: input_text.set_value
            target:
              entity_id: !input heating_mode_status_entity
            data:
              value: 'Eco'
          - if:
              - condition: template
                value_template: >
                  {{ eco_schedule_applied_scene is not none }}
            then:
              - action: scene.turn_on
                target:
                  entity_id: !input eco_schedule_applied_scene
